### PR TITLE
use Live server to serve static pages

### PR DESCRIPTION
**Pull request by ashleygwilliams**

### CODE REVIEW

**Comment by mikeal** [comment]
How does live-server know what to call for the re-build?

**Comment by ghost** [comment]
@mikeal i believe it just watches for file changes and then reloads? personally, i'd prefer putting the build step into `serve.js` and hooking nodemon up to watch for `.hbs` and `.md` changes

**Comment by ashleygwilliams** [comment]
sure that works for me @sup -- wanna make that PR? closing this one.

**Comment by mikeal** [comment]
What does "reload" mean in this context? When a file changes it needs to re-run the build and flush any cache there is.

**Comment by mikeal** [comment]
@sup right, but changes to a markdown file need to trigger a re-build in order to make a new .html file for that resource. when you have your browser up to view changes it's not looking at the templates and .md files, it's pulling up the built html, but now serve.js is only building it once. so what I'm wondering is, does this re-run serve.js on every change or is it just reloading the out of date html?

**Comment by ghost** [comment]
@mikeal it rebuilds every time and then serves the updates version

**Pull request closed without merging**
