### PR TITLE
Add languages support

### PR DESCRIPTION
**Pull request by xcatliu**
Hi @hackygolucky ,

I finished the localization of Node Live Beijing, then added some features. Now it's easy to add another language to this site. Please help to review the change of build script when you have time.

@JacksonTian @XadillaX Please help to review the translation.

Solved https://github.com/nodejs/Intl/issues/31

### CODE REVIEW

**Comment by hackygolucky** [comment]
ohmigosh. This is so rad! 

Thanks @xcatliu Verified as good on my end, but if you'd like to wait to have another person check the translation 🎉

**Comment by xcatliu** [comment]
@nodejs/nodejs-cn Can somebody help me check the translation? Thanks!

**Comment by haoxins** [comment]
I can review within this week!

**Comment by laosb** [comment]
All good :+1:! LGTM

**Comment by xcatliu** [comment]
Hi, @coderhaoxin 
Have you finished reviewing?

**Comment by haoxins** [comment]
LGTM

**Comment by xcatliu** [comment]
@laosb @coderhaoxin Thanks for your reviewing!
@hackygolucky It's ready to be merged now :)

**Comment by laosb** [comment]
Glad to see!

**Pull request merged**
